name: Combine Bot PRs

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

# The minimum permissions required to run this Action
permissions:
  contents: write
  pull-requests: write
  checks: read

jobs:
  combine-bot-prs:
    if: github.repository == 'gradle/android-cache-fix-gradle-plugin'
    runs-on: ubuntu-latest
    steps:
      - name: combine-bot-prs
        uses: github/combine-prs@v5.2.0
        with:
          branch_regex: ^(dependa|wrapper|renovate)bot\/.*$
          github_token: ${{ secrets.GH_BOT_GITHUB_TOKEN }}
