name: Execute Wrapper Upgrade

on:
  schedule:
    - cron:  '0 2 * * *'
  workflow_dispatch:

jobs:
  upgrade_wrapper:
    name: Execution
    runs-on: ubuntu-latest
    if: github.repository == 'gradle/android-cache-fix-gradle-plugin'
    steps:
      - name: Set up Git configuration
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git config --global url."https://unused-username:${TOKEN}@github.com/".insteadOf "https://github.com/"
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@01dd5d3ca463c7f10f7f4f7b4f177225ac661ee4
        with:
          gpg_private_key: ${{ secrets.GH_BOT_PGP_PRIVATE_KEY }}
          passphrase: ${{ secrets.GH_BOT_PGP_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_config_global: true
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3-beta
      - name: Upgrade Wrappers
        run: ./gradlew clean upgradeGradleWrapperAll --continue -Porg.gradle.java.installations.auto-download=false
        env:
          WRAPPER_UPGRADE_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_SOLUTIONS_ACCESS_TOKEN }}
